services:

  backend:
    build:
      dockerfile: dev.Dockerfile
    command: uvicorn fastapi_async_sql_profiler.main:app --reload --host 0.0.0.0 --port 80
    #command: bash -c "while true; do sleep 1000; done"
    container_name: fasp_backend
    environment:
      - POSTGRES_DB=fasp_bd
      - POSTGRES_HOST=fasp_postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - .:/app/:delegated # enable hot code reload in debug mode
      - ./data/backend/logs:/data/logs
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 80:80
      - 3001:3001

  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    container_name: fasp_postgres
    environment:
      # - TZ=Europe/Moscow
      - POSTGRES_DB=fasp_bd
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:rw
      - ./data/dumps:/mnt:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      interval: 2s
      timeout: 5s
      retries: 5